apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  labels:
    app: todo-app
spec:
  type: LoadBalancer
  selector:
    name: todo-app-pod
  ports:
  - name: http
    port: 8001
    targetPort: 8001
