apiVersion: v1
kind: Pod
metadata:
  name: todo-app-pod
  labels:
    name: todo-app-pod
spec:
  containers:
  - name: todo-app-pod
    image:  docker.io/ashishjangra/my-repo-123
    imagePullPolicy: Always
